version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "wemeet"
      POSTGRES_PASSWORD: "123123"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - 5432:5432
    restart: always
    expose:
      - 5432
    volumes:
      - app-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 5000:80
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=db; Port=5432; User Id=postgres; Password=123123; Database=wemeet"
    depends_on:
      - db
volumes:
  app-data:
