version: "3.7"

services:
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: "wemeet"
      PGDATA: "/var/lib/mysql/data"
    ports:
      - 3306:3306
    restart: always
    expose:
      - 3306
    volumes:
      - app-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 5000:5000
    restart: always
    environment:
      DB_CONNECTION_STRING: "server=db;user=root;password=123123;database=wemeet"
      BUILD_ENV: "docker"
    depends_on:
      - db
volumes:
  app-data:
