version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'wemeet'
      POSTGRES_PASSWORD: '123123'
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - 5432:5432
    expose:
      - 5432
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_CONNECTION_STRING: 'Server=db; Port=5432; User Id=postgres; Password=123123; Database=wemeet'
      BUILD_ENV: 'docker'
    depends_on:
      - db
volumes:
  app-db: {}
