version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "wemeet"
      POSTGRES_PASSWORD: "123123"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - 5432:5432
    restart: always
    expose:
      - 5432
    volumes:
      - app-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 80:5000
    restart: always
    environment:
      DB_CONNECTION_STRING: "Server=db; Port=5432; User Id=postgres; Password=123123; Database=wemeet"
      BUILD_ENV: "docker"
    depends_on:
      - db
volumes:
  app-data:
